---
- name: Enforce foo.txt
  hosts: all
  become: true
  tasks:
    - name: Ensure foo.txt contains only "foo"
      ansible.builtin.lineinfile:
        path: /home/larmbuster/git-repos/eda-filewatch-systemd/foo.txt
        regexp: '^FOO='
        line: FOO=foo
        create: true
        mode: '0644'
